name: Deployment - Reusable Workflow

on: 
    workflow_call: 
        inputs:
          mongodb-uri:
            required: true
            type: string
          kubectl_version:
            description: Provide the required kubectl version
            default: v1.27.0
            required: false
            type: string
          k8s-manifest-dir:
            description: Directory containin kubernetes manifest files
            default: kubernetes/
            required: true
            type: string
          environment:
            description: Provide the Deployment Environment
            default: dev
            required: true
            type: string
        secrets:
            k8s-kubeconfig:
                required: true
            mongodb-password:
                required: true
        outputs:
          application-url: 
            value: ${{  jobs.reuse-deploy.outputs.APP_INGRESS_URL }}
          
    
jobs:
    reuse-deploy:
        runs-on: ubuntu-latest
        environment: 
            name: ${{ inputs.environment }}
            url: https://${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST }}
        outputs:
            APP_INGRESS_URL: ${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST }}
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Install Kubectl CLI
              uses: azure/setup-kubectl@v4
              with:
                version: '${{ inputs.kubectl_version }}'  #default is latest stable

            - name: Set Kubeconfig File
              uses: azure/k8s-set-context@v4
              with:
                method: kubeconfig
                kubeconfig: ${{ secrets.k8s-kubeconfig }}
                #context: <context name> # current-context from kubeconfig is used as default

            - name: Fetch K8s Cluster details
              run: |
                kubectl version --short
                echo -------------------------------------------------------
                kubectl get nodes

            - name: Save Ingress Nginx Controller IP as a GITHUB Environment Variable #with in the same job or between steps of a job
              run: |
                echo "INGRESS_IP=$(kubectl -n ${{ vars.NAMESPACE }} get service ingress-nginx-controller -o jsonpath="{.status.loadBalancer.ingress[0].ip}")" >> $GITHUB_ENV
        
            - name: Replace Token in Manifest files
              uses: cschleiden/replace-tokens@v1
              with:
                tokenPrefix: '{'
                tokenSuffix: '}'
                files: '["${{ inputs.k8s-manifest-dir }}*.yaml"]'
              env:
                NAMESPACE: ${{ vars.NAMESPACE }}
                REPLICAS: ${{ vars.REPLICAS }}
                K8S_IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
                INGRESS_IP: ${{ env.INGRESS_IP }}

            - name: Check Files
              run: |
                cat ${{ inputs.k8s-manifest-dir }}*.yaml

            - name: Create MongoDB Secret
              run: |
                kubectl -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds \
                --from-literal=MONGO_URI=${{ inputs.mongodb-uri }} \
                --from-literal=MONGO_USERNAME=${{ vars.MONGO_USERNAME }} \
                --from-literal=MONGO_PASSWORD=${{ secrets.mongodb-password }} \
                --save-config \
                --dry-run=client \
                -o yaml | kubectl apply -f -
                
            - name: Deploy to ${{ inputs.environment }} Env
              run: |
                kubectl apply -f ${{ inputs.k8s-manifest-dir }}

            - name: Set App Ingress Host URl
              id: set-ingress-host-address
              run: |
                echo "APP_INGRESS_HOST=$(kubectl get -n ${{ vars.NAMESPACE }} ingress -o jsonpath="{.items[0].spec.tls[0].hosts[0]}")" >> $GITHUB_OUTPUT

        